# Generated by Django 2.0.1 on 2018-02-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='website',
        ),
    ]
